decoration:rounding = 12

decoration:blur:enabled = true
decoration:blur:size = 6
decoration:blur:passes = 3
decoration:blur:new_optimizations = true

decoration:shadow:enabled = true
decoration:shadow:range = 16
decoration:shadow:render_power = 3

