# -----------------------------------------------------
# Keyboard Layout (Hyprland 0.53.0)
# -----------------------------------------------------

# === Keyboard ===
input:kb_layout = us,th
input:kb_options = grp:ctrl_space_toggle
input:numlock_by_default = true

# === Mouse / Focus ===
input:follow_mouse = 1
input:sensitivity = 1

# === Key repeat ===
input:repeat_rate = 50
input:repeat_delay = 200

# -----------------------------------------------------
# Touchpad / Trackpad -> moved to conf/trackpad.conf
# -----------------------------------------------------
