# -----------------------------------------------------
# Keyboard Layout (Hyprland 0.53.0)
# -----------------------------------------------------

# === Keyboard ===
input:kb_layout = us,th
input:kb_options = grp:ctrl_space_toggle
input:numlock_by_default = true

# === Mouse / Focus ===
input:follow_mouse = 1
input:sensitivity = 1

# === Key repeat ===
input:repeat_rate = 50
input:repeat_delay = 200

# -----------------------------------------------------
# Touchpad (global)
# -----------------------------------------------------
input:touchpad:natural_scroll = true
input:touchpad:tap-to-click = true
input:touchpad:disable_while_typing = false
input:touchpad:scroll_factor = 1.2
input:touchpad:clickfinger_behavior = true
input:touchpad:middle_button_emulation = true

# -----------------------------------------------------
# Device specific (Trackpad override)
# -----------------------------------------------------
device = ps/2-synaptics-touchpad:sensitivity,3
device = ps/2-synaptics-touchpad:accel_profile,flat
device = ps/2-synaptics-touchpad:scroll_factor,3.0
