# -----------------------------------------------------
# Layouts (Hyprland 0.53.0)
# -----------------------------------------------------

# ---------- Dwindle ----------
#dwindle:pseudotile = true
dwindle:preserve_split = true

# ---------- Binds behavior ----------
binds:workspace_back_and_forth = true
binds:allow_workspace_cycles = true
binds:pass_mouse_when_bound = false
