# -----------------------------------------------------
# Misc settings (Hyprland 0.53.0)
# -----------------------------------------------------

misc:disable_hyprland_logo = true
misc:disable_splash_rendering = true
misc:initial_workspace_tracking = 1

# DisplayLink (evdi) flickers with hardware cursors
cursor:no_hardware_cursors = 1
