# -----------------------------------------------------
# Monitor Setup
# name: Default
# -----------------------------------------------------

# fallback (ถอดจอ / remote)
monitor = ,preferred,auto,1

# External Top-Left
monitor = HDMI-A-2,1920x1080@60,0x-1080,1

# Laptop panel (main)
monitor = eDP-1,1920x1080@60,0x0,1

# External Top-Right
monitor = DP-1,1920x1080@60,1920x-1080,1
