# -----------------------------------------------------
# General / Windows Layout (Hyprland 0.53.0)
# -----------------------------------------------------

general:layout = dwindle
general:gaps_in = 10
general:gaps_out = 14
general:border_size = 3
general:resize_on_border = true
general:allow_tearing = false

general:col.active_border = rgba(89b4faee) rgba(cba6f7ee) 45deg
general:col.inactive_border = rgba(45475aaa)
