# -----------------------------------------------------
# Window Rules (Hyprland 0.53.0)
# -----------------------------------------------------

# ---------- Browsers (force tile) ----------
windowrulev2 = tile,title:^(Microsoft-edge)$
windowrulev2 = tile,title:^(Brave-browser)$
windowrulev2 = tile,title:^(Chromium)$

# ---------- Utility apps (float) ----------
windowrulev2 = float,title:^(pavucontrol)$
windowrulev2 = float,title:^(blueman-manager)$
windowrulev2 = float,title:^(nm-connection-editor)$
windowrulev2 = float,title:^(qalculate-gtk)$

# ---------- Browser Picture-in-Picture ----------
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = pin,title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%,title:^(Picture-in-Picture)$

# ---------- Idle inhibit ----------
# modes: none | always | focus | fullscreen
windowrulev2 = idleinhibit fullscreen,class:.*
