source = ~/.config/hypr/colors.conf

source = ~/.config/hypr/conf/animation.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/cursor.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/keyboard.conf
source = ~/.config/hypr/conf/layerrules.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/windows.conf
