# Tmux Config
##### Basics #####
set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g mouse on
set -g escape-time 0
set -g status-right "%Y-%m-%d %H:%M"

##### Splits #####
bind - split-window -v         # horizontal split (below)
bind | split-window -h -p 25   # vertical split (right, 25%)

##### Pane navigation without the prefix key #####
# bind -n C-h select-pane -L
# bind -n C-j select-pane -D
# bind -n C-k select-pane -U
# bind -n C-l select-pane -R
# bind C-h select-pane -L
# bind C-j select-pane -D
# bind C-k select-pane -U
# bind C-l select-pane -R
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

##### Resize pane #####
bind -r < resize-pane -L 5
bind -r > resize-pane -R 5
bind -r + resize-pane -U 5
bind -r _ resize-pane -D 5

##### Rename window #####
bind N command-prompt -I "#W" "rename-window '%%'"

##### Kill pane without confirmation #####
unbind x
bind x kill-pane

##### TermguiColors ####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

