# Vibrant Kitty Theme

cursor               #ffcc00
cursor_text_color    #1e1e2e

foreground           #f8f8f2
background           #1e1e2e

selection_foreground #1e1e2e
selection_background #ffcc00

url_color            #8be9fd

